//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleTestV8.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuleTestV8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 S01400006943616368655465737465722E737265635C
        ///S31550000000033FFFF7821063709DE3800140000FEAC3
        ///S315500000102114001211140011D404214C901222F014
        ///S3155000002040000EEF921020044000117301000000B2
        ///S3155000003011140012D404214C9012216840000EE88D
        ///S31550000040921020002108003C92142078D0024000E3
        ///S3155000005090122102D0224000400010FB9010200246
        ///S31550000060400011039010200240001115A014200CDE
        ///S3155000007040000E9201000000D0040000900A3FF0AC
        ///S3155000008090122019D024000015080013110F3FFFBD
        ///S315500000909212A018901223FFD02240 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string iCacheTester1 {
            get {
                return ResourceManager.GetString("iCacheTester1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 S00D0000696F546573742E73726502
        ///S315500000009DE3BD98400001670100000040000212C8
        ///S3155000001001000000111400044000015C901223807E
        ///S315500000201114000340000159901223D8A007BDF8BF
        ///S31550000030400000C190100010D00FBDF880A220548F
        ///S315500000402280007DD00FBDF9400001F090102000B5
        ///S31550000050111400034000014D901223E011140004C6
        ///S31550000060D2022324808A600102800071A0102000F1
        ///S3155000007040000271010000004000022E9010203214
        ///S31550000080400002C601000000808A20FF1280000551
        ///S315500000902314000340000117901463E8A0102001B8
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string IoTesterSrec {
            get {
                return ResourceManager.GetString("IoTesterSrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon ModuleTest {
            get {
                object obj = ResourceManager.GetObject("ModuleTest", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 S01800004E6176537061726B496F5465737465722E73726563B7
        ///S315500000009DE3BF98400002CEA0102000400003059B
        ///S3155000001001000000400003A4010000001114000676
        ///S31550000020400001F5901223B011140005400001F272
        ///S31550000030901223F0400004A501000000808A20FFA2
        ///S315500000401280006D2714000511140006400001C5EA
        ///S3155000005090122000271400052514000623000007DF
        ///S3155000006040000547A0042001912A2010913220100B
        ///S3155000007092100008400003389014E3F8400001B98C
        ///S315500000809014A008400005C790146340400005C571
        ///S3155000009090146340400005 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string NavSparkIoTester {
            get {
                return ResourceManager.GetString("NavSparkIoTester", resourceCulture);
            }
        }
    }
}
